apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-deployment
  labels:
    app: petstore-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: vijesh89/jpetstore:7
        ports:
        - containerPort: 8080
