apiVersion: v1
kind: Service
metadata:
  name: service-petstore
  labels:
    app: service-petstore
spec:
  type: NodePort
  selector:
    app: petstore
  ports:
  - name: petstore-service-port
    protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 30007
