apiVersion: v1
kind: Service
metadata:
  name: service-petclinic
  labels:
    app: service-petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - name: petclinic-service-port
    protocol: TCP
    port: 8081
    targetPort: 8080
    nodePort: 30007
